language: python

notifications:
  email: false

python:
  - "2.7"
  - "3.4"
  - "3.5"
  - "3.6"

install:
    - sudo apt-get update -qq
    - sudo apt-get install -qq libhdf5-serial-dev 
    - pip uninstall numpy -y
    - pip install numpy>=1.10.4
    - pip install h5py

script:
    - python setup.py install
    - python testall.py
