# This workflow will install Python dependencies, run tests and lint with a variety of Python versions
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: CI

on:
  push:
  pull_request:
    branches: [master]

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        python-version: ["3.10", "3.11", "3.12"]
    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        shell: bash
        run: |
          python -m pip install --upgrade pip
          python -m pip install flake8 pytest

      - name: Lint with flake8
        shell: bash
        run: |
          # stop the build if there are Python syntax errors or undefined names
          flake8 . --count  --select=E9,F63,F7,F82 --show-source --statistics
          # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
          flake8 . --count --ignore=F401,W503,E203 --max-complexity=99 --max-line-length=127 --statistics

      - name: Install h5json
        shell: bash
        run: |
          pip install -e .

      - name: Checkout HSDS 
        uses: actions/checkout@v4
        with:
          repository: HDFGroup/hsds
          path: ${{github.workspace}}/hsds

      - name: Install HSDS
        working-directory: ${{github.workspace}}/hsds
        shell: bash
        run: |
          pip install -e .

      - name: Start HSDS
        shell: bash
        working-directory: ${{github.workspace}}/hsds
        run: |
          mkdir hsds_root
          mkdir hsds_root/hsds_bucket
          cp admin/config/groups.default admin/config/groups.txt
          cp admin/config/passwd.default admin/config/passwd.txt
          hsds --root_dir hsds_root --host localhost --port 5101 --password_file admin/config/passwd.txt --logfile hs.log --loglevel DEBUG --config_dir=admin/config --count=4 &

      - name: Wait for node startup
        shell: bash
        run: |
          sleep 30
      
      - name: HSDS Setup
        shell: bash
        env:
          ADMIN_PASSWORD: admin
          ADMIN_USERNAME: admin
        working-directory: ${{github.workspace}}/hsds
        run: |
          python tests/integ/setup_test.py

      - name: Run tests
        shell: bash
        env:
          HS_ENDPOINT: http://localhost:5101
          HS_USERNAME: test_user1
          HS_PASSWORD: test
        run: |
          python testall.py
